<?xml version="1.0" encoding="UTF-8" ?>
<firstLayout></firstLayout>
<gdVersion>
    <build>97</build>
    <major>4</major>
    <minor>0</minor>
    <revision>0</revision>
</gdVersion>
<properties>
    <adMobAppId></adMobAppId>
    <folderProject>false</folderProject>
    <linuxExecutableFilename></linuxExecutableFilename>
    <macExecutableFilename></macExecutableFilename>
    <orientation>landscape</orientation>
    <packageName>com.example.gamename</packageName>
    <projectFile>C:\Users\Agung_mp\GDevelop projects\My project13\game.json</projectFile>
    <sizeOnStartupMode>adaptWidth</sizeOnStartupMode>
    <useExternalSourceFiles>false</useExternalSourceFiles>
    <version>1.0.0</version>
    <winExecutableFilename></winExecutableFilename>
    <winExecutableIconFile></winExecutableIconFile>
    <name>Project</name>
    <author></author>
    <windowWidth>800</windowWidth>
    <windowHeight>600</windowHeight>
    <latestCompilationDirectory>E:\game</latestCompilationDirectory>
    <maxFPS>60</maxFPS>
    <minFPS>10</minFPS>
    <verticalSync>false</verticalSync>
    <platformSpecificAssets/>
    <loadingScreen>
        <showGDevelopSplash>true</showGDevelopSplash>
    </loadingScreen>
    <extensions>
        <name>BuiltinObject</name>
    </extensions>
    <extensions>
        <name>BuiltinAudio</name>
    </extensions>
    <extensions>
        <name>BuiltinVariables</name>
    </extensions>
    <extensions>
        <name>BuiltinTime</name>
    </extensions>
    <extensions>
        <name>BuiltinMouse</name>
    </extensions>
    <extensions>
        <name>BuiltinKeyboard</name>
    </extensions>
    <extensions>
        <name>BuiltinJoystick</name>
    </extensions>
    <extensions>
        <name>BuiltinCamera</name>
    </extensions>
    <extensions>
        <name>BuiltinWindow</name>
    </extensions>
    <extensions>
        <name>BuiltinFile</name>
    </extensions>
    <extensions>
        <name>BuiltinNetwork</name>
    </extensions>
    <extensions>
        <name>BuiltinScene</name>
    </extensions>
    <extensions>
        <name>BuiltinAdvanced</name>
    </extensions>
    <extensions>
        <name>Sprite</name>
    </extensions>
    <extensions>
        <name>BuiltinCommonInstructions</name>
    </extensions>
    <extensions>
        <name>BuiltinCommonConversions</name>
    </extensions>
    <extensions>
        <name>BuiltinStringInstructions</name>
    </extensions>
    <extensions>
        <name>BuiltinMathematicalTools</name>
    </extensions>
    <extensions>
        <name>BuiltinExternalLayouts</name>
    </extensions>
    <platforms>
        <name>GDevelop JS platform</name>
    </platforms>
    <currentPlatform>GDevelop JS platform</currentPlatform>
</properties>
<resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../1.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\1.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../2.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\2.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../3.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\3.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../4.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\4.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../5.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\5.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../6.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\6.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../8.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\8.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../9.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\9.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../10.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\10.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../11.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\11.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../NewFile-01.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\NewFile-01.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../5c1bbc51b0479.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\5c1bbc51b0479.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../5c1bbc37397de.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\5c1bbc37397de.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>../NewFile-1.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>..\NewFile-1.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>11.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>11.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>1.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>1.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>2.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>2.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>3.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>3.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>4.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>4.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>5.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>5.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>6.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>6.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>8.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>8.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>9.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>9.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>10.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>10.png</name>
        <smoothed>true</smoothed>
        <userAdded>false</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>NewFile-01.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>NewFile-01.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>5c1bbc51b0479.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>5c1bbc51b0479.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>5c1bbc37397de.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>5c1bbc37397de.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
    <resources>
        <alwaysLoaded>false</alwaysLoaded>
        <file>NewFile-1.png</file>
        <kind>image</kind>
        <metadata></metadata>
        <name>NewFile-1.png</name>
        <smoothed>true</smoothed>
        <userAdded>true</userAdded>
    </resources>
</resources>
<layouts>
    <b>209</b>
    <disableInputWhenNotFocused>true</disableInputWhenNotFocused>
    <mangledName>NewScene</mangledName>
    <name>NewScene</name>
    <oglFOV>90</oglFOV>
    <oglZFar>500</oglZFar>
    <oglZNear>1</oglZNear>
    <r>209</r>
    <standardSortMethod>true</standardSortMethod>
    <stopSoundsOnStartup>true</stopSoundsOnStartup>
    <title></title>
    <v>209</v>
    <uiSettings>
        <grid>false</grid>
        <gridB>255</gridB>
        <gridG>180</gridG>
        <gridHeight>32</gridHeight>
        <gridOffsetX>0</gridOffsetX>
        <gridOffsetY>0</gridOffsetY>
        <gridR>158</gridR>
        <gridWidth>32</gridWidth>
        <snap>true</snap>
        <windowMask>false</windowMask>
        <zoomFactor>1</zoomFactor>
    </uiSettings>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>64</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject2</name>
        <width>1758</width>
        <x>-484</x>
        <y>553</y>
        <zOrder>1</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>90</height>
        <layer></layer>
        <locked>false</locked>
        <name>itit</name>
        <width>98</width>
        <x>-23</x>
        <y>467</y>
        <zOrder>2</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>110</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject3</name>
        <width>104</width>
        <x>87</x>
        <y>448</y>
        <zOrder>3</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>56</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject5</name>
        <width>172</width>
        <x>677</x>
        <y>556</y>
        <zOrder>4</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>40</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject2</name>
        <width>132</width>
        <x>209</x>
        <y>366</y>
        <zOrder>5</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>110</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject3</name>
        <width>104</width>
        <x>243</x>
        <y>256</y>
        <zOrder>3</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>40</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject2</name>
        <width>132</width>
        <x>391</x>
        <y>196</y>
        <zOrder>5</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>32</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject4</name>
        <width>64</width>
        <x>464.695</x>
        <y>541.5</y>
        <zOrder>6</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>32</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject4</name>
        <width>50</width>
        <x>249</x>
        <y>350</y>
        <zOrder>6</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>32</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject4</name>
        <width>64</width>
        <x>157</x>
        <y>534</y>
        <zOrder>6</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>110</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject3</name>
        <width>104</width>
        <x>507</x>
        <y>454</y>
        <zOrder>3</zOrder>
    </instances>
    <instances>
        <angle>0</angle>
        <customSize>true</customSize>
        <height>40</height>
        <layer></layer>
        <locked>false</locked>
        <name>NewObject2</name>
        <width>132</width>
        <x>673</x>
        <y>288</y>
        <zOrder>5</zOrder>
    </instances>
    <objects>
        <name>itit</name>
        <type>Sprite</type>
        <updateIfNotVisible>false</updateIfNotVisible>
        <behaviors>
            <acceleration>1500</acceleration>
            <canGrabPlatforms>false</canGrabPlatforms>
            <deceleration>1500</deceleration>
            <gravity>1000</gravity>
            <ignoreDefaultControls>false</ignoreDefaultControls>
            <jumpSpeed>600</jumpSpeed>
            <maxFallingSpeed>700</maxFallingSpeed>
            <maxSpeed>250</maxSpeed>
            <name>PlatformerObject</name>
            <slopeMaxAngle>60</slopeMaxAngle>
            <type>PlatformBehavior::PlatformerObjectBehavior</type>
            <xGrabTolerance>10</xGrabTolerance>
            <yGrabOffset>0</yGrabOffset>
        </behaviors>
        <animations>
            <name></name>
            <useMultipleDirections>false</useMultipleDirections>
            <directions>
                <looping>true</looping>
                <timeBetweenFrames>0.08</timeBetweenFrames>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>11.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>1.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>2.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>3.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>4.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>5.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>6.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>8.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>9.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
                <sprites>
                    <hasCustomCollisionMask>false</hasCustomCollisionMask>
                    <image>10.png</image>
                    <originPoint>
                        <name>origine</name>
                        <x>0</x>
                        <y>0</y>
                    </originPoint>
                    <centerPoint>
                        <automatic>true</automatic>
                        <name>centre</name>
                        <x>0</x>
                        <y>0</y>
                    </centerPoint>
                </sprites>
            </directions>
        </animations>
    </objects>
    <objects>
        <height>32</height>
        <name>NewObject2</name>
        <texture>NewFile-01.png</texture>
        <type>TiledSpriteObject::TiledSprite</type>
        <width>32</width>
        <behaviors>
            <canBeGrabbed>true</canBeGrabbed>
            <name>Platform</name>
            <platformType>NormalPlatform</platformType>
            <type>PlatformBehavior::PlatformBehavior</type>
            <yGrabOffset>0</yGrabOffset>
        </behaviors>
    </objects>
    <objects>
        <height>32</height>
        <name>NewObject3</name>
        <texture>5c1bbc51b0479.png</texture>
        <type>TiledSpriteObject::TiledSprite</type>
        <width>32</width>
        <behaviors>
            <canBeGrabbed>true</canBeGrabbed>
            <name>Platform</name>
            <platformType>NormalPlatform</platformType>
            <type>PlatformBehavior::PlatformBehavior</type>
            <yGrabOffset>0</yGrabOffset>
        </behaviors>
    </objects>
    <objects>
        <height>32</height>
        <name>NewObject4</name>
        <texture>5c1bbc37397de.png</texture>
        <type>TiledSpriteObject::TiledSprite</type>
        <width>32</width>
        <behaviors>
            <canBeGrabbed>true</canBeGrabbed>
            <name>Platform</name>
            <platformType>NormalPlatform</platformType>
            <type>PlatformBehavior::PlatformBehavior</type>
            <yGrabOffset>0</yGrabOffset>
        </behaviors>
    </objects>
    <objects>
        <height>32</height>
        <name>NewObject5</name>
        <texture>NewFile-1.png</texture>
        <type>TiledSpriteObject::TiledSprite</type>
        <width>32</width>
    </objects>
    <layers>
        <name></name>
        <visibility>true</visibility>
        <cameras>
            <defaultSize>true</defaultSize>
            <defaultViewport>true</defaultViewport>
            <height>0</height>
            <viewportBottom>1</viewportBottom>
            <viewportLeft>0</viewportLeft>
            <viewportRight>1</viewportRight>
            <viewportTop>0</viewportTop>
            <width>0</width>
        </cameras>
    </layers>
    <behaviorsSharedData>
        <name>Platform</name>
        <type>PlatformBehavior::PlatformBehavior</type>
    </behaviorsSharedData>
    <behaviorsSharedData>
        <name>PlatformerObject</name>
        <type>PlatformBehavior::PlatformerObjectBehavior</type>
    </behaviorsSharedData>
</layouts>
